JedisUtils shouldn&apos;t wrap unknow Exception
The project I&amp;apos;m working on has 2 data access configuration, one with Spring-data-jpa, and an other with Spring-data-redis. 
Since I added the JedisConnectionFactory as a Spring bean, one of my JPA-based junit failed because it attempts to catch a DataIntegrityViolationException. But instead this exception is wrapped into a JedisSystemException (see JedisUtils.convertJedisAccessException()).
When I read the code in ChainedPersistenceExceptionTranslator, I understand that a PersistenceExceptionTranslator that doesn&amp;apos;t handle an exception should return null. So I think JedisUtils.convertJedisAccessException() should return null also in case of unhandled exception.