FilterListIterator#hasNext throws exception (associate with JUnit tests)
Hi,
I found the some of the iterator classes does not fulfill the iterator specification of JDK.
e.g. hasNext() should never throw exception.
Here is an automatically generated junit test (I am now writing a tool)


public void test233() throws Throwable {
    java.lang.Integer var6 = new java.lang.Integer(0);
    org.apache.commons.collections.list.GrowthList var7 = new org.apache.commons.collections.list.GrowthList(var6);
    org.apache.commons.collections.Predicate var9 = org.apache.commons.collections.PredicateUtils.anyPredicate((java.util.Collection)var7);
    java.lang.Long var10 = new java.lang.Long(10L);
    org.apache.commons.collections.iterators.FilterListIterator var13 = new org.apache.commons.collections.iterators.FilterListIterator(var9);
    //this line throws exception!
    var13.hasNext();
}


could you please check it to confirm whether it is bug or I misunderstand the specification of apache common collections?
thanks,